{% set version = "1.3.2" %}
{% set major,minor,patch = version.split('.') %}

package:
  name: libwebp-base
  version: {{ version }}

source:
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-{{ version }}.tar.gz
  sha256: 2a499607df669e40258e53d0ade8035ba4ec0175244869d1025d460562aa09b4

build:
  number: 0
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libwebp
    - {{ pin_subpackage('libwebp-base') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake    # [win]
    - ninja    # [win]
    - libtool  # [unix]
    - make     # [unix]
  run_constrained:
    # 1.1 is when libwebp-base was split from libwebp
    - libwebp {{ version }}

{% set libraries = ["libwebp", "libwebpdemux", "libwebpmux", "libwebpdecoder", "libsharpyuv"] %}
{% set headers = ["decode.h", "demux.h", "encode.h", "mux_types.h", "mux.h", "types.h"] %}
{% set binaries = ["cwebp", "dwebp", "gif2webp", "img2webp", "webpinfo", "webpmux"] %}

test:
  commands:
    {% for each_lib in libraries %}
    - otool -L $PREFIX/lib/{{ each_lib }}.dylib    # [osx]
    {% endfor %}

about:
  home: https://developers.google.com/speed/webp
  license: BSD-3-Clause
  license_file: COPYING
  summary: WebP image library
  description: >
    WebP is a method of lossy and lossless compression that can be used on a large variety of photographic, translucent and graphical images found on the web. The degree of lossy compression is adjustable so a user can choose the trade-off between file size and image quality. libwebp-base provides the headers and shared
    libraries. For cwebp and dwep, binaries install libwebp.
  doc_url: https://developers.google.com/speed/webp/docs/using
  dev_url: https://chromium.googlesource.com/webm/libwebp

extra:
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
